# Generated by Django 5.2.3 on 2025-06-12 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_create_user_profiles'),
        ('end_customers', '0001_initial'),
        ('major_clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('end_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoped_data', to='end_customers.endcustomer')),
                ('freight_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoped_data', to='major_clients.freightcompany')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_datasc_content_64e4ac_idx'), models.Index(fields=['freight_company'], name='core_datasc_freight_1aee8d_idx'), models.Index(fields=['end_customer'], name='core_datasc_end_cus_423c55_idx')],
            },
        ),
    ]
