# Generated by Django 5.2.3 on 2025-06-12 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreightCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('saas_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freight_companies', to='superadmin.saasprovider')),
            ],
            options={
                'verbose_name': 'Freight Company',
                'verbose_name_plural': 'Freight Companies',
            },
        ),
    ]
