# Generated by Django 5.2.3 on 2025-06-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_customers', '0002_alter_endcustomer_freight_companies'),
        ('major_clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freightcompany',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freightcompany',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='freightcompany',
            name='end_customers',
            field=models.ManyToManyField(related_name='+', to='end_customers.endcustomer'),
        ),
        migrations.AddField(
            model_name='freightcompany',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
