# Generated by Django 5.2.3 on 2025-06-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaaSProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'SaaS Provider',
                'verbose_name_plural': 'SaaS Providers',
            },
        ),
    ]
