# Generated by Django 5.2.3 on 2025-06-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('major_clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('freight_companies', models.ManyToManyField(related_name='end_customers', to='major_clients.freightcompany')),
            ],
            options={
                'verbose_name': 'End Customer',
                'verbose_name_plural': 'End Customers',
            },
        ),
    ]
