# Generated by Django 5.2.3 on 2025-06-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_customers', '0001_initial'),
        ('major_clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endcustomer',
            name='freight_companies',
            field=models.ManyToManyField(related_name='freight_companies', to='major_clients.freightcompany'),
        ),
    ]
