# Generated by Django 5.2.3 on 2025-06-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('end_customers', '0002_alter_endcustomer_freight_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='endcustomer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endcustomer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='endcustomer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
